- build.gradle
> RD: Fixing the broken healthcheck.

- charts/rd-caseworker-ref-api/Chart.yaml
- charts/rd-caseworker-ref-api/values.preview.template.yaml
- charts/rd-caseworker-ref-api/values.yaml
- src/main/resources/application.yaml
- src/main/resources/bootstrap.yml
https://tools.hmcts.net/jira/browse/AM-960
```
[ ] Yes
[X] No
```
> Adding chart configuration

- charts/rd-caseworker-ref-api/Chart.yaml
- charts/rd-caseworker-ref-api/values.yaml
https://tools.hmcts.net/jira/browse/AM-960
```
[ ] Yes
[X] No
```
> Testing PR

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- infrastructure/aat.tfvars
- infrastructure/main.tf
- infrastructure/provider.tf
- infrastructure/state.tf
- infrastructure/terraform.tf
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/RDCC-1910
```
[ ] Yes
[X] No
```
> TF upgrade to 0.12.16 and Azure RM upgrade to 2.20.0 - Master

- Jenkinsfile_CNP
- Jenkinsfile_nightly
- audit.json
- charts/rd-caseworker-ref-api/Chart.yaml
- charts/rd-caseworker-ref-api/values.preview.template.yaml
- charts/rd-caseworker-ref-api/values.yaml
- src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/WelcomeFuncTest.java
- src/functionalTest/resources/application-functional.yaml
- src/main/resources/bootstrap.yml
feat:Nighlty build fix
```
[ ] Yes
[X ] No
```
> Nighlty build fix

- src/main/resources/db/migration/V1_1__init_tables.sql
- src/main/resources/db/migration/V1_2__add_sequences.sql
- src/main/resources/db/migration/V1_3__insert_queries_role_user_type.sql
feat:rdcc-1989
feat:adding the flyway scripts for rd-case-worker-api
```
[ ] Yes
[X] No
```
> feat:adding the flyway scripts for rd-case-worker-api

- build.gradle
- src/main/java/uk/gov/hmcts/reform/cwrdapi/controllers/advice/CaseworkerMessageFailedException.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/servicebus/TopicPublisher.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/servicebus/messaging/JmsErrorHandler.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/servicebus/messaging/MessagingConfig.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/cwrdapi/servicebus/TopicPublisherTest.java
- src/test/java/uk/gov/hmcts/reform/cwrdapi/servicebus/messaging/JmsErrorHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/cwrdapi/servicebus/messaging/MessagingConfigTest.java
https://tools.hmcts.net/jira/browse/RDCC-1979
Azure Service Bus Changes
```
[ ] Yes
[x] No
```
> RDCC-1979: Azure Service Bus Changes

- src/main/resources/db/migration/V1_1__init_tables.sql
RDCC-1989
feat:updating unique constraint value
```
[ ] Yes
[X] No
```
> Rdcc 1989 1

- charts/rd-caseworker-ref-api/Chart.yaml
- src/main/resources/application.yaml
feat: charts changes
```
[ ] Yes
[X ] No
```
> feat:charts changes

- src/main/resources/db/migration/V1_2__insert_queries_role_user_type.sql
feat: updating the queries
```
[ ] Yes
[ X] No
```
> feat:updating the role names

- README.md
- src/main/java/uk/gov/hmcts/reform/cwrdapi/servicebus/TopicPublisher.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/servicebus/messaging/JmsErrorHandler.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/servicebus/messaging/MessagingConfig.java
- src/test/java/uk/gov/hmcts/reform/cwrdapi/servicebus/TopicPublisherTest.java
- src/test/java/uk/gov/hmcts/reform/cwrdapi/servicebus/messaging/JmsErrorHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/cwrdapi/servicebus/messaging/MessagingConfigTest.java
feat: commenting the jmc code in AAT
```
[ ] Yes
[ X] No
```
> Jms code comment

- audit.json
N/A
Nightly Fix: adding entries to audit.json
```
[ ] Yes
[x] No
```
> Nightly Fix: adding entries to audit.json 

- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-2107
Fix CVES
```
[ ] Yes
[ X] No
```
> fixed Nightly builds

- build.gradle
- charts/rd-caseworker-ref-api/Chart.yaml
- charts/rd-caseworker-ref-api/values.preview.template.yaml
- charts/rd-caseworker-ref-api/values.yaml
- config/owasp/suppressions.xml
- infrastructure/main.tf
- src/main/resources/bootstrap.yml
https://tools.hmcts.net/jira/browse/RDCC-2141
```
[ ] Yes
[X] No
```
> Manage s2s secret using TF and update references

- charts/rd-caseworker-ref-api/Chart.yaml
- charts/rd-caseworker-ref-api/values.preview.template.yaml
- charts/rd-caseworker-ref-api/values.yaml
- src/main/resources/bootstrap.yml
https://tools.hmcts.net/jira/browse/RDCC-2141
```
[ ] Yes
[X] No
```
> Add reference to s2s secret

- src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/client/CaseWorkerApiClient.java
RDCC-2077
RDCC-2077: Forcing the email id to lower case in functional tests.
```
[ ] Yes
[x] No
```
> RDCC-2077: Forcing the email id to lower case in functional tests.

- audit.json
RDCC-2168
adding entries to `audit.json`
```
[ ] Yes
[x] No
```
> RDCC-2168: Fixing Sexurity Scan issues

- audit.json
https://tools.hmcts.net/jira/browse/RDCC-2168
adding entries to audit.json
```
[ ] Yes
[x] No
```
> RDCC-2168: Fixing Nightly Build (Security Scan)

- audit.json
Adding entries to audit.json
```
[ ] Yes
[x] No
```
> Nightly Build Fix: Security Scan

- src/main/java/uk/gov/hmcts/reform/cwrdapi/domain/CaseWorkerProfile.java
- src/main/resources/db/migration/V1_5__remove_delete_date_column.sql
- src/test/java/uk/gov/hmcts/reform/cwrdapi/domain/CaseWorkerProfileTest.java
https://tools.hmcts.net/jira/browse/RDCC-2232
adding sql script to drop column 'delete_date'
```
[ ] Yes
[x] No
```
> RDCC-2232: removing column 'delete_date'

- src/functionalTest/resources/application-functional.yaml
- src/main/resources/application.yaml
Pointed UP to aat env instead of preview
```
[ ] Yes
[x] No
```
> build: Pointed UP to aat env instead of preview

- src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/CaseWorkerRefCreateTest.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/controllers/CaseWorkerRefController.java
- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RDCC-2230
(feat) RDCC-2230 : Updating the required roles for FetchUsersById.
```
[ ] Yes
[x] No
```
> (feat) RDCC-2230 : Updating the required roles for FetchUsersById.

- src/main/java/uk/gov/hmcts/reform/cwrdapi/client/domain/CaseWorkerProfile.java
RDCC-2373
This is to fix the Idam role entity in response object
```
[ ] Yes
[X ] No
```
> fix: Ignore IDAM roles entity when it is null(RDCC-2373)

- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RDCC-2365
Adding `XUI_WEBAPP` to `CRD_S2S_AUTHORISED_SERVICES`
Linked to: https://github.com/hmcts/cnp-flux-config/pull/7932
```
[ ] Yes
[x] No
```
> RDCC-2365: adding 'XUI_WEBAPP' to Authorised Services

- src/main/java/uk/gov/hmcts/reform/cwrdapi/service/impl/CaseWorkerServiceImpl.java
RDCC-2371
fix :RDCC-2371 - update flow role matching fixed
```
[ ] Yes
[X] No
```
> fix :RDCC-2371 - update flow role matching fixed

- Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/RDCC-2254
```
[ ] Yes
[X] No
```
> Sync ithc and perftest branches with master

- charts/rd-caseworker-ref-api/Chart.yaml
- charts/rd-caseworker-ref-api/values.yaml
Adding necessary variables in values.yaml.
NA
Adding necessary variables in values.yaml.
```
[ ] Yes
[x] No
```
> Adding necessary variables in values.yaml.

- src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/service/ValidationServiceFacadeImplTest.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/repository/AuditRepository.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/service/IValidationService.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/service/impl/CaseWorkerServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/service/impl/ValidationServiceFacadeImpl.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/util/AuditInterceptor.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/util/CaseWorkerConstants.java
- src/test/java/uk/gov/hmcts/reform/cwrdapi/util/AuditInterceptorTest.java
https://tools.hmcts.net/jira/browse/RDCC-2333
fix: addressed review comments
No
> fix: addressed review comments

- audit.json
- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-2462
Fixed CVE 2021-21290 by upgrading netty version
```
[ ] Yes
[x] No
```
> build: Fixed CVE 2021-21290

- infrastructure/main.tf
same as https://github.com/hmcts/rd-professional-api/pull/925
see https://tools.hmcts.net/confluence/display/DTSPO/%5BSelf-Service%5D+Database
> Enable self service DB access

- src/main/java/uk/gov/hmcts/reform/cwrdapi/service/impl/CaseWorkerServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/service/impl/ExcelAdaptorServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/servicebus/TopicPublisher.java
- src/test/java/uk/gov/hmcts/reform/cwrdapi/service/ExcelAdaptorServiceImplTest.java
https://tools.hmcts.net/jira/browse/RDCC-2433
Added job id and row id in logs
```
[ ] Yes
[x] No
```
> fix: RDCC-2433 Added job id and row id in logs

- build.gradle
- config/owasp/suppressions.xml
- src/test/java/uk/gov/hmcts/reform/cwrdapi/service/impl/CaseWorkerServiceFacadeImplTest.java
- src/test/java/uk/gov/hmcts/reform/cwrdapi/service/impl/CaseWorkerServiceImplTest.java
RDCC-2507
This PR addressed the Jar bump up versions and audit ison issues
```
[ ] Yes
[X ] No
```
> DependBot : Upgrade libs versions (Rdcc 2507)

- charts/rd-caseworker-ref-api/Chart.yaml
- charts/rd-caseworker-ref-api/values.preview.template.yaml
- charts/rd-caseworker-ref-api/values.yaml
- src/main/resources/bootstrap.yml
https://tools.hmcts.net/jira/browse/RDCC-2505
```
[ ] Yes
[X] No
```
> Update app insights key secret name

- src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/CaseWorkerCreateUserWithFileUploadTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/CaseWorkerSuspendUserWithFileUploadTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/CaseWorkerUpdateUserWithFileUploadTest.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/client/domain/CaseWorkerProfile.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/controllers/advice/ExceptionMapper.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/service/impl/ExcelAdaptorServiceImpl.java
- src/test/java/uk/gov/hmcts/reform/cwrdapi/controllers/advice/ExceptionMapperTest.java
This PR addresses below issues
- In correct display of row id when the record has some errors
- RegionId is shown in error message when the record has no region selected
- Getting 500 error without any error message
```
[ ] Yes
[x] No
```
> fix: RDCC-2437 Removed the validation on region Id and fixed row id issue

- config/owasp/suppressions.xml
Removed unwanted suppression of cves, as they are being fixed already
```
[ ] Yes
[x] No
```
> fix: Removed unwanted suppression of cves

- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RDCC-2442
Increased batch size to 30. Please have a look at the comment section in the JIRA for the analysis done for batch size
```
[ ] Yes
[x] No
```
> fix: Increased batch size to 30

- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RDCC-2632
added hikari configuration
```
[ ] Yes
[x] No
```
> fix: RDCC-2632 added hikari configuration

- build.gradle
NA
Added memory limits to integration tests.
```
[ ] Yes
[x] No
```
> Added memory limits to integration tests.

- src/main/java/uk/gov/hmcts/reform/cwrdapi/oidc/JwtGrantedAuthoritiesConverter.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/util/MappingField.java
- src/test/java/uk/gov/hmcts/reform/cwrdapi/util/AuditInterceptorTest.java
https://tools.hmcts.net/jira/browse/RDCC-2662
Addressing Sonar Smells: 
https://sonarcloud.io/project/issues?id=uk.gov.hmcts.reform%3Areform%3A%3Ard-caseworker-ref-api&resolved=false
```
[ ] Yes
[x] No
```
> Fix: Addressing Code smells

- build.gradle
- src/contractTest/java/uk/gov/hmcts/reform/cwrdapi/FetchCaseworkersByIdProviderTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/CaseWorkerCreateUserWithFileUploadTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/config/TestConfig.java
- src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/util/AuthorizationEnabledIntegrationTest.java
- src/integrationTest/resources/application-test.yml
- src/main/java/uk/gov/hmcts/reform/cwrdapi/domain/CaseWorkerLocation.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/domain/CaseWorkerProfile.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/domain/CaseWorkerRole.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/domain/CaseWorkerWorkArea.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/domain/RoleType.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/service/impl/CaseWorkerServiceImpl.java
https://tools.hmcts.net/jira/browse/RDCC-2449
refactor: JPA query tuning (RDCC-2499)
No
>  refactor: JPA query tuning (RDCC-2499)

- src/main/java/uk/gov/hmcts/reform/cwrdapi/service/impl/CaseWorkerServiceImpl.java
RDCC-2481
Updating the error message from IDAM.
```
[ ] Yes
[x] No
```
> RDCC-2481: Updating the error message from IDAM.

- build.gradle
- src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/CaseWorkerCreateUserWithFileUploadTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/CaseWorkerSuspendUserWithFileUploadTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/CaseWorkerUpdateUserWithFileUploadTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/FileUploadTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/config/TestConfig.java
- src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/util/AuthorizationEnabledIntegrationTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/util/IntegrationTestOidcSecurityConfig.java
https://tools.hmcts.net/jira/browse/RDCC-2646
RDCC-2646: Initial checkin to fix performance issues for the Integration test cases.
```
[ ] Yes
[x] No
```
> RDCC-2646: Fix performance issues for the Integration test cases.

- build.gradle
RDCC-2646
Fix heap memory issues.
```
[ ] Yes
[x] No
```
> (fix): Remove memory limits.

- charts/rd-caseworker-ref-api/Chart.yaml
https://tools.hmcts.net/jira/browse/RDCC-2746
Helm chart version is upgraded
```
[ ] Yes
[X ] No
```
> fix:RDCC-2746: Helm chart version upgrade

- Jenkinsfile_CNP
- src/contractTest/java/uk/gov/hmcts/reform/cwrdapi/FetchCaseworkersByIdProviderTest.java
RDCC-2762
RDCC-2762 : add pact test report for CW
```
[ ] Yes
[X] No
```
> add pact test report

- audit.json
JIRA link
https://tools.hmcts.net/jira/browse/RDCC-2777
Change description
Fixed security scan reported issue
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[x] No
> fix: RDCC-2777 Fixed security scan reported issue

- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-2894
Upgraded springboot version to fix CVE CVE-2021-22112
```
[ ] Yes
[x] No
```
> fix: RDCC-2894 Upgraded springboot version

- src/contractTest/java/uk/gov/hmcts/reform/cwrdapi/StaffReferenceDataProviderTest.java
https://tools.hmcts.net/jira/browse/RDCC-2729
Modified PACT test for refresh role endpoint
```
[ ] Yes
[x] No
```
> feat: Modified PACT for refresh role endpoint

- Jenkinsfile_nightly
> added configuration for serenity report in nighly job

- build.gradle
JIRA link
https://tools.hmcts.net/jira/browse/RDCC-3047
Change description
Fixed Pact not being verified issue
```
[ ] Yes
[x] No
```
> fix: RDCC-3047 Fixed PACTs not being verified issue

- build.gradle
RDCC-3150
This change is to remove the Bintray reference
```
[ ] Yes
[ X] No
```
> fix: Remove bintray reference(RDCC-3150)

- charts/rd-caseworker-ref-api/Chart.yaml
- src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/AuthorizationFunctionalTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/client/FuncTestRequestHandler.java
https://tools.hmcts.net/jira/browse/RDCC-2820
- Fixed failing test due to changes in UP email removal
```
[ ] Yes
[x] No
```
> fix: RDCC-2820 Fixed failing test due to changes in UP email removal

- src/main/java/uk/gov/hmcts/reform/cwrdapi/controllers/CaseWorkerRefController.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/controllers/CaseWorkerRefUsersController.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/service/impl/CaseWorkerServiceFacadeImpl.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/service/impl/CaseWorkerServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/service/impl/ExcelAdaptorServiceImpl.java
JIRA link
https://tools.hmcts.net/jira/browse/RDCC-2262
Change description
CRD - Remove the log added for time taken for executing methods and code for handling formula cell type
Does this PR introduce a breaking change? (check one with "x")
```
[ ] Yes
[ X ] No
> RDCC-2262 - removed log to check the time taken for executing methods

- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-3166
Removed integration tests from mutation coverage and lowered threshold
```
[ ] Yes
[x] No
```
> RDCC-3166: Fixing serenity report

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RDCC-3237
Fix CVE issue : CVE-2021-28170
```
[ ] Yes
[X] No
```
> RDCC-3237 - Fix CVE issue : CVE-2021-28170, CVE-2021-22119

- src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/service/ExcelUploaderTest.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/service/impl/CaseWorkerServiceFacadeImpl.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/service/impl/ExcelValidatorServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/util/CaseWorkerConstants.java
- src/test/java/uk/gov/hmcts/reform/cwrdapi/service/ExcelValidatorServiceImplTest.java
https://tools.hmcts.net/jira/browse/RDCC-3297
Fixes for the issues identified in the Fortify scan. 
```
[ ] Yes
[x] No
```
> RDCC-3297: Fortify - Fix Caseworker repo fortify issues

- infrastructure/terraform.tf
NA
Fix TF build errors "Failed to marshal state to json: unsupported attribute "name""
```
[ ] Yes
[X] No
```
> Add Azure AD TF provider

- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-3557
Upgraded spring core version to fix CVE-2021-22096
```
[ ] Yes
[x] No
```
> fix: RDCC-3557 Upgraded spring core version to fix CVE-2021-22096

- src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/util/serenity5/counter/TestCountListener.java
- src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/util/serenity5/extension/page/SerenityPageExtension.java
- src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/FileUploadTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/util/IntegrationTestOidcSecurityConfig.java
- src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/util/serenity5/counter/TestCountListener.java
- src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/util/serenity5/extension/page/SerenityPageExtension.java
https://tools.hmcts.net/jira/browse/RDCC-3634
Replaced the deprecated method and added the valid method in use
```
[ ] Yes
[x] No
```
> fix: RDCC-3634 Replaced the deprecated method and added the valid method in use

- Jenkinsfile_nightly
- src/contractTest/java/uk/gov/hmcts/reform/cwrdapi/UserProfileConsumerTest.java
https://tools.hmcts.net/jira/browse/RDCC-3840
- Enabled fortify scan
- Added appropriate idam status in pact
```
[ ] Yes
[x] No
```
> fix: RDCC-3840 Enabled fortify scan

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/AuthorizationFunctionalTest.java
- src/smokeTest/java/uk/gov/hmcts/reform/cwrdapi/SmokeTest.java
https://tools.hmcts.net/jira/browse/RDCC-3477
```
[ ] Yes
[ X] No
```
> Upgrade Gradle Version 7.3.3

- audit.json
- build.gradle
fix: Used used testImplementation instead of testCompile
> fix: Used used testImplementation instead of testCompile

- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-4088
Fix nightly build failure due to CWE-862: Missing Authorization
```
[ ] Yes
[x] No
```
> fix: Added spring security dependency explicitly 

- charts/rd-caseworker-ref-api/Chart.yaml
https://tools.hmcts.net/jira/browse/RDCC-4139
Updated java chart version to 3.7.3
```
[ ] Yes
[x] No
```
> fix: Updated java chart version to 3.7.3

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RDCC-4307
CVE Fix for CVE-2022-26336
```
[ ] Yes
[X] No
```
> RDCC-4307-SRD Nightly Build Failure

- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-4293
```
[ ] Yes
[X] No
```
> Rdcc 4293-Functional Test Reports Not Generating

- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-4321
Collating DependaBot PRs
```
[ ] Yes
[x] No
```
> RDCC-4321: Collating DependaBot PRs

- src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/config/WireMockExtension.java
JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/RDCC-4297
Change description
- Staff Reference API  - Improve integration test case timings 
- Updated wiremock setup
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[x] No
> RDCC-4297 : Staff Reference API  - Improve integration test case timings 

- src/main/java/uk/gov/hmcts/reform/cwrdapi/controllers/advice/ExceptionMapper.java
- src/test/java/uk/gov/hmcts/reform/cwrdapi/controllers/advice/ExceptionMapperTest.java
https://tools.hmcts.net/jira/browse/RDCC-4251
Added handle for verbose error messages
```
[ ] Yes
[x] No
```
> RDCC-4251: SRD - Handle Verbose Error Messages

- Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/RDCC-4363
adding step `enableDbMigration('rd')` in `Jenkinsfile_CNP` in DEMO
```
[ ] Yes
[x] No
```
> (DEMO) RDCC-4363: adding step enableDbMigration('rd') in Jenkinsfile_CNP

- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RDCC-4363
> RDCC-4363: adding POSTGRES-DATABASE secret to main.tf

- infrastructure/main.tf
RDCC-4363: adding missing DB related secrets
https://tools.hmcts.net/jira/browse/RDCC-4363
> RDCC-4363: adding missing DB related secrets

- Jenkinsfile_CNP
- infrastructure/main.tf
RDCC-4363: reverting changes in Demo
> RDCC-4363: reverting changes in Demo

- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-4427
CVE fix
```
[ ] Yes
[x] No
```
> RDCC-4427: CVE fix

- README.md
- src/test/java/uk/gov/hmcts/reform/cwrdapi/service/ExcelAdaptorServiceImplTest.java
- src/test/java/uk/gov/hmcts/reform/cwrdapi/service/ValidationServiceFacadeTest.java
- src/test/java/uk/gov/hmcts/reform/cwrdapi/service/impl/CaseWorkerServiceImplTest.java
- src/test/java/uk/gov/hmcts/reform/cwrdapi/service/impl/FeatureToggleServiceImplTest.java
> Fix Sonar Issue in SRD

- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-4504
fix for CVE-2022-22968 
```
[ ] Yes
[X ] No
```
> SRD Nightly build failure -25/04/2022

- src/main/java/uk/gov/hmcts/reform/cwrdapi/controllers/CaseWorkerRefUsersController.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/service/impl/CaseWorkerServiceImpl.java
https://tools.hmcts.net/jira/browse/RDCC-4614
Changes made to fix sonar issues
```
[ ] Yes
[ x] No
```
> RDCC-4614:Changes made to fix sonar issues

- src/main/java/uk/gov/hmcts/reform/cwrdapi/controllers/CaseWorkerRefUsersController.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/repository/CaseWorkerProfileRepository.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/service/impl/CaseWorkerServiceImpl.java
https://tools.hmcts.net/jira/browse/RDCC-4614
To fix sonar issues
```
[ ] Yes
[ x] No
```
> Feat:To fix sonar issues

- build.gradle
CVE Fix for tomcat embed
```
[ ] Yes
[X] No
```
> CVEFix for tomcat embed

- build.gradle
Mutation tests are failing
https://tools.hmcts.net/jira/browse/RDCC-4700
```
[ ] Yes
[X] No
```
> RDCC-4700 :SRD Nightly Build failure

- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-4614
Changes made to fix app-insights issue
```
[ ] Yes
[ x] No
```
> RDCC-4614:Changes made to fix logger issues

- .dockerignore
- Dockerfile
- acb.tpl.yaml
https://tools.hmcts.net/jira/browse/RDCC-4717
Added multi-architecture ACR Task template
```
[ ] Yes
[x] No
```
> feat: Added multi-architecture ACR Task template

- .github/dependabot.yml
https://tools.hmcts.net/jira/browse/RDCC-4898
Deleted dependabot yaml file as Renovate changes are already in place to upgrade the dependencies automatically
```
[ ] Yes
[x] No
```
> RDCC-4898 Delete dependabot yaml file

- charts/rd-caseworker-ref-api/Chart.yaml
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RDCC-5005
Updated service bus chart version to latest
```
[ ] Yes
[x] No
```
> RDCC-5005: Update the chart version of service bus and blob storage to the latest

- charts/rd-caseworker-ref-api/Chart.yaml
- charts/rd-caseworker-ref-api/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/RDCC-5033
Upgrade java chart 
```
[ ] Yes
[x] No
```
> RDCC-5033 Upgrade java chart

- src/integrationTest/resources/db/testmigration/V1_12__update_usertype.sql
- src/integrationTest/resources/db/testmigration/V1_16__update_roletype.sql
- src/integrationTest/resources/db/testmigration/V1_7__insert_update_queries_role_type.sql
- src/integrationTest/resources/db/testmigration/V1_8__insert_queries_role_type.sql
- src/integrationTest/resources/db/testmigration/V1_9__insert_queries_role_types.sql
https://tools.hmcts.net/jira/browse/RDCC-5178
Changes made to sync flywayscripts
```
[ ] Yes
[x ] No
```
> Feat:RDCC-5178:Changes made to sync flywayscripts

- src/main/java/uk/gov/hmcts/reform/cwrdapi/controllers/StaffRefDataController.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/service/StaffRefDataService.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/service/impl/StaffRefDataServiceImpl.java
https://tools.hmcts.net/jira/browse/RDCC-5417
Skeleton for Staff UI 
```
[ ] Yes
[x] No
```
> RDCC-5417 - Created Controller and service skeleton

- src/integrationTest/resources/db/testmigration/V1_17__staff_ui_tables.sql
- src/main/resources/db/migration/V1_17__staff_ui_tables.sql
> staff ui tables script

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RDCC-5447
Suppress CVEs CVE-2022-38749, CVE-2022-38750, CVE-2022-38751
```
[ ] Yes
[x] No
```
> RDCC-5447: Suppress Snakeyaml CVEs

- build.gradle
- charts/rd-caseworker-ref-api/values.preview.template.yaml
- src/contractTest/java/uk/gov/hmcts/reform/cwrdapi/StaffReferenceDataProviderTest.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/controllers/request/StaffProfileCreationRequest.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/domain/CaseWorkerSkill.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/service/IJsrValidatorInitializer.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/service/IJsrValidatorStaffProfile.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/service/IStaffProfileAuditService.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/service/IValidationService.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/service/impl/JsrValidatorInitializer.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/service/impl/JsrValidatorStaffProfile.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/service/impl/StaffProfileAuditServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/service/impl/StaffRefDataServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/service/impl/ValidationServiceFacadeImpl.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/util/CaseWorkerConstants.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/cwrdapi/TestSupport.java
- src/test/java/uk/gov/hmcts/reform/cwrdapi/service/JsrValidatorInitializerTest.java
- src/test/java/uk/gov/hmcts/reform/cwrdapi/service/impl/JsrValidatorStaffProfileTest.java
- src/test/java/uk/gov/hmcts/reform/cwrdapi/service/impl/StaffRefDataServiceImplTest.java
- src/test/java/uk/gov/hmcts/reform/cwrdapi/service/impl/StaffRefDataServiceTest.java
- src/test/java/uk/gov/hmcts/reform/cwrdapi/util/EmailValidatorTest.java
https://tools.hmcts.net/jira/browse/RDCC-5647
```
[ ] Yes
[ X] No
```
> Rdcc 5647 fixes

- audit.json
nightly build fix 
Does this PR introduce a breaking change?
```
[ ] Yes
[ X] No
```
> Fixing nightly build - ignoring owasp scan for new api's

- audit.json
Nightly build fix
**Does this PR introduce a breaking change?
```
[ ] Yes
[ X] No
```
> Nightly build fix

- infrastructure/prod.tfvars
Create Replica database for Staff in Production
JIRA link : https://tools.hmcts.net/jira/browse/RDCC-5624
Change description : MI Reporting : Create Replica database for Staff in Production
Does this PR introduce a breaking change?
```
[ ] Yes
[ X] No
```
> Create Replica database for Staff in Production

- audit.json
Nightly Build Fix: Adding Entries to audit.json
```
[ ] Yes
[x] No
```
> Nightly Build Fix: Adding Entries to audit.json

- audit.json
Nightly Fix: Adding entries to audit.json
```
[ ] Yes
[x] No
```
> Nightly Fix: Adding entries to audit.json

- build.gradle
CVE Fix for Postgresql
```
[ ] Yes
[X] No
```
> cve fix issue

- build.gradle
- src/main/java/uk/gov/hmcts/reform/cwrdapi/controllers/request/StaffProfileCreationRequest.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/controllers/response/SearchStaffUserResponse.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/service/impl/StaffRefDataServiceImpl.java
- src/test/java/uk/gov/hmcts/reform/cwrdapi/service/impl/StaffRefDataUpdateStaffServiceImplTest.java
https://tools.hmcts.net/jira/browse/RDCC-6137
Updated response with new field
```
[ ] Yes
[x] No
```
> RDCC-6137: Staff : Add Caseworker ID to the Staff basic search & advanced search APIs

- charts/rd-caseworker-ref-api/Chart.yaml
https://tools.hmcts.net/jira/browse/RDCC-6137
Upgraded chart version
```
[ ] Yes
[x] No
```
> Upgrade java chart version

- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-6332
Fix for CVE-2022-40152
```
[ ] Yes
[x] No
```
> RDCC-6332: Fix for CVE-2022-40152

- charts/rd-caseworker-ref-api/Chart.yaml
https://tools.hmcts.net/jira/browse/RDCC-1707
Upgraded helm chart version to `4.0.11`
```
[ ] Yes
[x] No
```
> RDCC-1707: Upgrade helm chart version to latest

- charts/rd-caseworker-ref-api/Chart.yaml
https://tools.hmcts.net/jira/browse/RDCC-6374
Upgrading chart version to `4.0.13`
```
[ ] Yes
[x] No
```
> RDCC-6374: Upgrading chart version to `4.0.13`

- charts/rd-caseworker-ref-api/Chart.yaml
- src/contractTest/java/uk/gov/hmcts/reform/cwrdapi/StaffReferenceDataProviderTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/StaffRefDataIntegrationTest.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/controllers/StaffRefDataController.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/repository/SkillRepository.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/service/StaffRefDataService.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/service/impl/StaffRefDataServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/util/RequestUtils.java
- src/test/java/uk/gov/hmcts/reform/cwrdapi/controllers/StaffRefDataControllerTest.java
- src/test/java/uk/gov/hmcts/reform/cwrdapi/service/impl/StaffRefDataServiceImplTest.java
https://tools.hmcts.net/jira/browse/RDCC-6343
Staff : Filter the list of Skills based on Service Code
```
[ ] Yes
[x ] No
```
> Feat:Staff : Filter the list of Skills based on Service Code

- .github/renovate.json
https://tools.hmcts.net/jira/browse/RDCC-6421
RDCC-6421-renovate.json update
```
[ ] Yes
[x] No
```
> RDCC-6421-renovate.json update

- audit.json
Security Scan issues
```
[ ] Yes
[X] No
```
> security scan issues

- build.gradle
- config/owasp/suppressions.xml
- src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/FetchStaffProfileByIdFunctionalTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/FetchStaffProfileByIdIntegrationTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/util/AuthorizationEnabledIntegrationTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/util/CaseWorkerReferenceDataClient.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/config/WebMvcConfig.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/controllers/StaffRefDataController.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/controllers/feign/UserProfileFeignClient.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/controllers/response/SearchStaffUserByIdResponse.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/service/StaffRefDataService.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/service/impl/FeatureToggleServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/service/impl/StaffRefDataServiceImpl.java
- src/test/java/uk/gov/hmcts/reform/cwrdapi/controllers/StaffRefDataControllerTest.java
- src/test/java/uk/gov/hmcts/reform/cwrdapi/service/impl/StaffRefDataServiceImplTest.java
Fetch Staff Profile By Id
```
[ ] Yes
[X] No
```
> Fetch Staff Profile By Id

- audit.json
Reverts hmcts/rd-caseworker-ref-api#683
> Revert "addressed security scan issues"

- audit.json
https://tools.hmcts.net/jira/browse/RDCC-6534
addresses security scan issues flagged during nightly build
```
[ ] Yes
[x] No
```
> addressed security scan issues

- src/contractTest/java/uk/gov/hmcts/reform/cwrdapi/StaffReferenceDataProviderTest.java
https://tools.hmcts.net/jira/browse/RDCC-6526
Added pact test for the fetchStaffProfileByID endpoint
```
[ ] Yes
[x] No
```
> RDCC-6526: Pact Test Coverage for Fetch StaffProfileByID endpoint

- config/owasp/suppressions.xml
Suppressed `CVE-2023-20860`
```
[ ] Yes
[x] No
```
> CRD CVE Suppression

- audit.json
https://tools.hmcts.net/jira/browse/DTSRD-156
Change to audit.json to prevent nightly build failure
```
[ ] Yes
[x] No
```
> Ignore warnings from nightly build

- audit.json
https://tools.hmcts.net/jira/browse/DTSRD-202
```
[ ] Yes
[X] No
```
> DTSRD-202 - suppress 10096_Timestamp for robots.txt GET

- build.gradle
https://tools.hmcts.net/jira/browse/DTSRD-295
https://tools.hmcts.net/jira/browse/DTSRD-296
addresses CVE-2023-20873
remedied in spring-boot 2.7.11 - https://spring.io/security/cve-2023-20873
addresses CVE-2023-20862
remedied in spring-security 5.7.8 - https://spring.io/security/cve-2023-20862
```
[ ] Yes
[x] No
```
> addresses CVE-2023-20873,  CVE-2023-20862

- src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/FetchStaffProfileByIdFunctionalTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/StaffRefCreateFunctionalTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/StaffRefDataSkillsFunctionalTest.java
- src/main/resources/db/migration/V1_21__Delete_skill_TestSkill.sql
Delete test skills in skill table
```
[ ] Yes
[ X] No
```
> To Delete test skills in skill table

- src/main/resources/db/migration/V1_22__update_skill_table.sql
https://tools.hmcts.net/jira/browse/RDCC-6750
[RDCC-6750]Staff UI : Add new Skills for Family Private Law
```
[ ] Yes
[x ] No
```
> [RDCC-6750]Staff UI : Add new Skills for Family Private Law

- Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/RDCC-6200
[RDCC-6200] Fix for delete functional test user
```
[ ] Yes
[ x] No
```
> [RDCC-6200] Fix for delete functional test user

- deletescript/sql/delete-functional-test-data.sql
https://tools.hmcts.net/jira/browse/RDCC-6200
[RDCC-6200] Sql query to delete functional test users from diff tables
```
[ ] Yes
[ x] No
```
> [RDCC-6200] Sql query to delete functional test users from diff tables

- deletescript/sql/delete-functional-test-data.sql
https://tools.hmcts.net/jira/browse/RDCC-6200
[RDCC-6200] Sql query to delete functional test users from skill table
```
[ ] Yes
[ x] No
```
> [RDCC-6200] Sql query to delete functional test users from skill table

- src/test/java/uk/gov/hmcts/reform/cwrdapi/service/CaseWorkerProfileConverterTest.java
- src/test/java/uk/gov/hmcts/reform/cwrdapi/service/impl/CaseWorkerDeleteServiceImplTest.java
- src/test/java/uk/gov/hmcts/reform/cwrdapi/service/impl/StaffRefDataServiceImplTest.java
https://tools.hmcts.net/jira/browse/RDCC-6753
```
[ ] Yes
[X] No
```
> SRD: Test Cases can be clubbed as Parameterised tests

- src/main/java/uk/gov/hmcts/reform/cwrdapi/util/CaseWorkerChildListValidator.java
https://tools.hmcts.net/jira/browse/DTSRD-52
Fixed 500 error when primary location is null and a secondary location is present
```
[ ] Yes
[x] No
```
> Fixed 500 error when primary location is null

- src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/CreateCaseWorkerProfilesIntegrationTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/CreateUpdateStaffRefDataProfilesIntegrationTest.java
- src/integrationTest/resources/db/testmigration/V1_20__insert_roletype.sql
- src/main/resources/db/migration/V1_24__insert_roletype.sql
> DTSRD-742, DTSRD-541: add new roles

- build.gradle
> Address CVE-2023-34034

- .github/renovate.json
- Jenkinsfile_CNP
- build.gradle
- charts/rd-caseworker-ref-api/values.preview.template.yaml
> Fix CVE-2023-39533

- config/owasp/suppressions.xml
> CVE CVE-2022-26336 suppression

- audit.json
DTSRD-1173
```
[ ] Yes
[* ] No
```
> DTSRD-1173.Nightly builds failing with OWASP Zaproxy error

- infrastructure/main.tf
- infrastructure/terraform.tf
- infrastructure/variables.tf
DTSRD- 1245
```
[ ] Yes
[ *] No
```
> DTSRD- 1245 Upgrade Postgres V15

- infrastructure/main.tf
- infrastructure/terraform.tf
- infrastructure/variables.tf
> DTSRD-1245 upgrade postgres

- infrastructure/main.tf
- infrastructure/output.tf
- infrastructure/variables.tf
DTSRD-1245
```
[ ] Yes
[ ] No
```
> DTSRD-1245

- infrastructure/main.tf
- infrastructure/output.tf
- infrastructure/variables.tf
DTSRD-1245
```
[ ] Yes
[ ] No
```
> DTSRD-1245.Postgres upgrade v15

- Jenkinsfile_CNP
DTSRD-1446
```
[ ] Yes
[ ] No
```
> DTSRD-1446.Remove branches to sync -caseworker demo and master

- Jenkinsfile_CNP
- build.gradle
- infrastructure/main.tf
- infrastructure/terraform.tf
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/DTSRD-1248
```
[ ] Yes
[ *] No
```
> DTSRD-1248.Upgrade to postgres V15 . - merge demo to perftest

- Jenkinsfile_CNP
- build.gradle
DTSRD-1466
```
[ ] Yes
[ ] No
```
> Adding CVE fix from master and removing sync to ithc before merging V15 changes

- infrastructure/main.tf
- infrastructure/terraform.tf
- infrastructure/variables.tf
DTSRD-1247
```
[ ] Yes
[ ] No
```
> DTSRD-1247.merging V15 changes made to ithc and perftest

- Jenkinsfile_CNP
- build.gradle
> adding cve fix to perftest

- src/contractTest/java/uk/gov/hmcts/reform/cwrdapi/CommonDataApiConsumerTest.java
https://tools.hmcts.net/jira/browse/RDCC-7093
Common : Consumer Pact Test Cases needs to be added
```
[ ] Yes
[ x] No
```
> [RDCC-7093]Common : Consumer Pact Test Cases needs to be added

- charts/rd-caseworker-ref-api/Chart.yaml
- charts/rd-caseworker-ref-api/values.preview.template.yaml
- charts/rd-caseworker-ref-api/values.yaml
- config/owasp/suppressions.xml
- src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/CaseWorkerRefFunctionalTest.java
- src/functionalTest/resources/application-functional.yaml
- src/integrationTest/resources/application-test.yml
- src/main/java/uk/gov/hmcts/reform/cwrdapi/service/impl/CaseWorkerServiceFacadeImpl.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/util/CaseWorkerConstants.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/cwrdapi/service/impl/CaseWorkerServiceFacadeImplTest.java
https://tools.hmcts.net/jira/browse/RDCC-7102
```
[ ] Yes
[X] No
```
> Staff : Block Staff upload Template

- src/main/resources/application.yaml
> Update application.yaml. reverting connection string

- src/contractTest/java/uk/gov/hmcts/reform/cwrdapi/UserProfileConsumerTest.java
- src/contractTest/java/uk/gov/hmcts/reform/cwrdapi/request/DeleteUserProfilesRequest.java
https://tools.hmcts.net/jira/browse/RDCC-7097
[RDCC-7097]UP : Consumer Pact Test Cases needs to be added
```
[ ] Yes
[x ] No
```
> [RDCC-7097]UP : Consumer Pact Test Cases needs to be added

- src/main/resources/application.yaml
> flyway schema change

- config/owasp/suppressions.xml
Suppresses CVE-2023-36052 (likely a false positive)
```
[ ] Yes
[x] No
```
> Suppress CVE-2023-36052

- build.gradle
- src/contractTest/java/uk/gov/hmcts/reform/cwrdapi/StaffReferenceDataProviderTest.java
> Update dependencycheck to use default version

- Jenkinsfile_CNP
- infrastructure/main.tf
- infrastructure/terraform.tf
- infrastructure/variables.tf
> DTSRD-1893.Upgrading main branch to V16 and adding subnet_suffix

- charts/rd-caseworker-ref-api/Chart.yaml
- charts/rd-caseworker-ref-api/values.yaml
> DTSRD-2442: PI33 Configure spot instances in non-production

- infrastructure/main.tf
> Update schema ownership 1

- build.gradle
- database/Dockerfile
- src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/util/CaseworkerRefApiPostgresqlContainer.java
- src/integrationTest/resources/application-test.yml
> Update build.gradle - upgrade flyway-fixing master build

- build.gradle
> Fix DB Migration issues

- build.gradle
> Fix db issue

- infrastructure/main.tf
- infrastructure/variables.tf
> create replica server

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/DTSRD-2801
Addresses CVE-2023-1370
```
[ ] Yes
[x] No
```
> DTSRD-2801

- infrastructure/terraform.tf
Update azurerm to 3.105.0 to fix build pipeline
```
[ ] Yes
[x] No
```
> Update azurerm to 3.105.0

- build.gradle
> Update build.gradle. Fix build

- src/main/resources/testcontainers.properties
Testcontainers.org configuration moved to Jenkins builds
```
[ ] Yes
[ ] No
```
> Cleanup - delete testcontainers.properties

- Dockerfile
- acb.tpl.yaml
- build.gradle
https://tools.hmcts.net/jira/browse/DTSRD-3356
Java 21 upgrade
```
[ ] Yes
[ ] No
```
> DTSRD-3356

- src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/CreateCaseWorkerProfilesIntegrationTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/CreateUpdateStaffRefDataProfilesIntegrationTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/StaffRefDataIntegrationTest.java
- src/integrationTest/resources/db/testmigration/V1_22__insert_roletype.sql
- src/main/resources/db/migration/V1_26__insert_roletype.sql
- src/test/java/uk/gov/hmcts/reform/cwrdapi/controllers/CaseWorkerRefUsersControllerTest.java
> DTSRD-3358: Create New FTA Role for IBCA in RD

- src/main/java/uk/gov/hmcts/reform/cwrdapi/service/impl/CaseWorkerServiceImpl.java
> DTSRD-3448: Log staff profile count returned from DB and returned in response

- build.gradle
> Fix flyway migration issue

- build.gradle
Enable verbose logging to diagnose nightly build failure
```
[ ] Yes
[x] No
```
> Nightly build failure - increase Pitest log level

- .github/workflows/swagger.yml
- src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/docs/SwaggerPublisherTest.java
- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/DTSRD-3562
Swagger Publishing
```
[ ] Yes
[x] No
```
> Dtsrd 3562 swagger publishing

- src/main/java/uk/gov/hmcts/reform/cwrdapi/config/SwaggerConfiguration.java
> swagger api

- infrastructure/variables.tf
> Set default thresholds to 70%

- infrastructure/variables.tf
Reverts hmcts/rd-caseworker-ref-api#995
> Revert "Set default thresholds to 70%"

- infrastructure/main.tf
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/CME-247
```
[ ] Yes
[ x] No
```
> CME-122: Database monitoring and alerting on RD repositories

- Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/CME-247
Testing completed so sync can be re-enabled.
```
[ ] Yes
[x ] No
```
> CME-247: Enable sync to ITHC for database monitoring

- infrastructure/terraform.tf
https://tools.hmcts.net/jira/browse/CME-297
```
[ ] Yes
[ x] No
```
> CME-297: Update azurerm

- charts/rd-caseworker-ref-api/Chart.yaml
https://tools.hmcts.net/jira/browse/CME-407
```
[ ] Yes
[ x] No
```
> CME-407: Update OCI endpoint

- src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/CreateCaseWorkerProfilesIntegrationTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/CreateUpdateStaffRefDataProfilesIntegrationTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/StaffRefDataIntegrationTest.java
- src/integrationTest/resources/db/testmigration/V1_24__insert_roletype.sql
- src/main/resources/db/migration/V1_29__insert_roletype.sql
- src/test/java/uk/gov/hmcts/reform/cwrdapi/controllers/CaseWorkerRefUsersControllerTest.java
https://tools.hmcts.net/jira/browse/COT-958
Added new role for WLU Administrator
```
[ ] Yes
[X] No
```
> COT-958 Added new role WLU Administrator

- src/integrationTest/resources/application-test.yml
- src/main/resources/application.yaml
> DTSRD-4521.Extend email domain list to include IBCA users

- Jenkinsfile_nightly
- build.gradle
https://tools.hmcts.net/jira/browse/DTSRD-4101
Added fortify dependency
```
[ ] Yes
[x] No
```
> DTSRD-4101
