hmcts/rd-caseworker-ref-api

- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-2107
Fixed CVE-2020-13956 CVE-2020-25638 CVE-2020-17527 by upgrading
- httpclient
- hibernate-core
- tomcat-embed-core
- tomcat-embed-websocket
```
[ ] Yes
[x] No
```
> build: Fixed CVE-2020-13956 CVE-2020-25638 CVE-2020-17527

- src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/CaseWorkerRefCreateTest.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/controllers/CaseWorkerRefController.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/controllers/response/CaseWorkerProfileCreationResponse.java
- src/test/java/uk/gov/hmcts/reform/cwrdapi/controllers/CaseWorkerRefControllerTest.java
- src/test/java/uk/gov/hmcts/reform/cwrdapi/controllers/response/CaseWorkerProfileCreationResponseTest.java
https://tools.hmcts.net/jira/browse/RDCC-2207
Send case worker ids in the response once CW profiles are created
```
[ ] Yes
[x] No
```
> feat: Send case worker ids in the response once CW profiles are created

- src/integrationTest/resources/application-test.yml
- src/main/java/uk/gov/hmcts/reform/cwrdapi/controllers/CaseWorkerRefController.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/service/impl/CaseWorkerServiceImpl.java
- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RDCC-2436
This PR addresses the below review comments
- This check seems to be redundant and can be removed
if (workbook.getNumberOfSheets() < 1) { // check at least 1 sheet present throw new ExcelValidationException(HttpStatus.BAD_REQUEST, FILE_NO_DATA_ERROR_MESSAGE); }
- The following code should be inside the if condition — > if (isNotEmpty(processedCwProfiles)) {
CaseWorkerProfileCreationResponse.CaseWorkerProfileCreationResponseBuilder caseWorkerProfileCreationResponse =
CaseWorkerProfileCreationResponse
.builder()
.caseWorkerRegistrationResponse(REQUEST_COMPLETED_SUCCESSFULLY);
- modifyCaseWorkerUserStatus() And modifyCaseWorkerUser() methods look same. One of them can be removed.
- Set hibernate.order_updates to true
- Set batch_size to 20
**Does …
> fix: RDCC-2436 Refactored code by removing unwanted codes and renamed methods

- build.gradle
- src/main/java/uk/gov/hmcts/reform/cwrdapi/service/impl/ExcelAdaptorServiceImpl.java
https://tools.hmcts.net/jira/browse/RDCC-2436
Fixed the below review comment 
- 1. This check seems to be redundant and can be removed
if (workbook.getNumberOfSheets() < 1) { // check at least 1 sheet present throw new ExcelValidationException(HttpStatus.BAD_REQUEST, FILE_NO_DATA_ERROR_MESSAGE); }
and 
- fixed CVE-2021-22112 by upgrading springboot version
```
[ ] Yes
[x] No
```
> fix: RDCC-2436 Removed redundant code and fixed CVE CVE-2021-22112

- src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/CaseWorkerCreateUserWithFileUploadTest.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/util/AuditInterceptor.java
https://tools.hmcts.net/jira/browse/RDCC-2478
Scenario to reproduce the issue mentioned in the ticket
- Create a user with invalid role
- Upload a file.
- For the same user add role "cwd-admin".
- Upload the same file
```
[ ] Yes
[x] No
```
> fix: RDCC-2478 Avoided to create audit for user with invalid role

- build.gradle
- src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/util/AuthorizationEnabledIntegrationTest.java
Upgrade the Netty Jar to fix CVE-2021-21409
```
[ ] Yes
[x] No
```
> Upgrade the Netty Jar to fix CVE-2021-21409

- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-2743
Upgraded apache commons io version to latest to fix CVE-2021-29425
```
[ ] Yes
[x] No
```
> fix: Upgraded apache commons io version to latest to fix CVE-2021-29425

- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-2106
Since Compile and testCompile entries are deprecated from gradle 7 hence changed all the Compile and testCompile entries in the build.gradle file to Implementation and testImplementation.
```
[ ] Yes
[ X] No
```
> RDCC-2106  changed all Compile and testCompile entries

- src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/CaseWorkerRefFunctionalTest.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/controllers/advice/ExceptionMapper.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/controllers/advice/StaffReferenceException.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/controllers/internal/StaffReferenceInternalController.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/service/impl/CaseWorkerServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/util/CaseWorkerConstants.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/util/JsonFeignResponseUtil.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/util/RequestUtils.java
- src/test/java/uk/gov/hmcts/reform/cwrdapi/controllers/advice/ExceptionMapperTest.java
- src/test/java/uk/gov/hmcts/reform/cwrdapi/controllers/advice/StaffReferenceExceptionTest.java
- src/test/java/uk/gov/hmcts/reform/cwrdapi/controllers/internal/StaffReferenceInternalControllerTest.java
- src/test/java/uk/gov/hmcts/reform/cwrdapi/service/impl/CaseWorkerServiceImplTest.java
- src/test/java/uk/gov/hmcts/reform/cwrdapi/util/RequestUtilsTest.java
https://tools.hmcts.net/jira/browse/RDCC-2925
Handled following observations
- When we supply more than one column in sorting column we get 404 instead 400
- When we supply invalid service name ( * or special char )it shows 404 instead 400
```
[ ] Yes
[x] No
```
> fix: RDCC-2925 Handled invalid request

- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-3167
Upgraded the commons-compress to address CVE-2021-35515 CVE-2021-35516, CVE-2021-35517, CVE-2021-36090
```
[ ] Yes
[x] No
```
> fix:RDCC-3167 Upgraded the commons-compress to address CVE-2021-35515 CVE-2021-35516, CVE-2021-35517, CVE-2021-36090

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RDCC-3254
RDCC-3254 - added CVE-2020-23171 entry in suppressions.xml
```
[X] Yes
[ ] No
```
> RDCC-3254 - added CVE-2020-23171 entry in suppressions.xml

- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-4633
Fixed CVE CVE-2022-25647 by upgrading gson and LD
```
[ ] Yes
[x] No
```
> fix: RDCC-4633 Fixed CVE CVE-2022-25647 by upgrading gson and LD

- src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/CaseWorkerRefFunctionalTest.java
https://tools.hmcts.net/jira/browse/RDCC-5181
Fixed the failing functional test case by making the service to idam test cases to be executed first
```
[ ] Yes
[x] No
```
> fix: RDCC-5181 Fixed the failing functional test case

- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-5261
Upgrading `postgresql` to `42.4.1` to fix `CVE-2022-31197`
```
[ ] Yes
[x] No
```
> RDCC-5261: Upgrading postgresql to 42.4.1

- src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/CaseWorkerRefFunctionalTest.java
fix: Fixed the failing test by providing invalid ccd service name
```
[ ] Yes
[x] No
```
> fix: Fixed the failing test by providing invalid ccd service name

- audit.json
ignoring owasp scan for new api's
Does this PR introduce a breaking change?
```
[ ] Yes
[ X] No
```
> Fixing nightly build - ignoring owasp scan for new api's

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RDCC-6061
Adding Suppression for `CVE-2022-41881` as latest version of netty still contains CVE.
```
[ ] Yes
[x] No
```
> RDCC-6061: Adding Suppression for `CVE-2022-41881`

- build.gradle
- config/owasp/suppressions.xml
[
](https://tools.hmcts.net/jira/browse/DTSRD-151)
Upped spring framework to a version that doesn't have the vulnerability
https://nvd.nist.gov/vuln/detail/CVE-2023-20860 
```
[ ] Yes
[x] No
```
> Upped spring framework version to fix CVE-2023-20860

- src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/StaffRefDataAdvancedSearchFunctionalTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/CreateStaffReferenceProfileBasicSearchTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/CreateStaffReferenceProfileIntegrationTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/util/CaseWorkerReferenceDataClient.java
- src/main/java/uk/gov/hmcts/reform/cwrdapi/util/CaseWorkerConstants.java
- src/test/java/uk/gov/hmcts/reform/cwrdapi/controllers/StaffRefDataControllerTest.java
- src/test/java/uk/gov/hmcts/reform/cwrdapi/service/impl/JsrValidatorStaffProfileTest.java
- src/test/java/uk/gov/hmcts/reform/cwrdapi/util/RequestUtilsTest.java
https://tools.hmcts.net/jira/browse/RDCC-6697
Search by name  API regex  correction
```
[ ] Yes
[x] No
```
> RDCC-6697 : Search by name API regex correction

- build.gradle
- charts/rd-caseworker-ref-api/Chart.yaml
- Updating Netty versions for CVE-2023-4586.
- Updating helm version; Version of java helm chart below 5.0.0 is deprecated, please upgrade to latest release https://github.com/hmcts/chart-java/releases This configuration will stop working by 23/10/2023
https://tools.hmcts.net/jira/browse/DTSRD-1456
DTSRD-1456
- Updating Netty versions for CVE-2023-4586.
- Updating helm version; Version of java helm chart below 5.0.0 is deprecated, please upgrade to latest release https://github.com/hmcts/chart-java/releases This configuration will stop working by 23/10/2023
```
[ ] Yes
[x] No
```
> DTSRD-1456

- Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/CME-247
Changes for https://github.com/hmcts/rd-caseworker-ref-api/pull/992 needs to be tested in ITHC.
```
[ ] Yes
[ x] No
```
> CME-247: Disable sync to ITHC for database monitoring testing

- infrastructure/main.tf
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/CME-247
```
[ ] Yes
[ x] No
```
> CME-122: Database monitoring and alerting on RD repositories
